### PR TITLE
Updates to Maven, fixing Ant build

### PR DESCRIPTION
**Pull request by iliat**

### CODE REVIEW

**Comment by pgrosu** [comment]
Hey Ilia,

Looks and works great, but it might help to update the example in the Readme file to something like this, which does not depend on using the fullpath via `readlink` and has a minor fix with referencing the `client_secrets.json` file:

```Bash
java -jar -Dsamjdk.custom_reader=\
https://www.googleapis.com/genomics,\
com.google.cloud.genomics.gatk.htsjdk.GA4GHReaderFactory,\
`pwd`/target/gatk-tools-java-1.0-SNAPSHOT.jar \
-Dga4gh.client_secrets=client_secrets.json \
dist/picard.jar ViewSam INPUT=https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/
```
Currently the `client_secrets.json` argument is shown as follows (which contains a forward slash), and above I also used the bundled jar file from the `target` directory after performing `maven bundle:bundle`:

```Bash
-Dga4gh.client_secrets=/client_secrets.json \
```

It might be good to guide users how they can download and setup Picard, through a few simple steps like this:

```Bash
wget https://github.com/broadinstitute/picard/releases/download/1.129/picard-tools-1.129.zip
unzip unzip picard-tools-1.129.zip
mv picard-tools-1.129 dist
```

Anyways looks pretty awesome :)

Thanks,
~p

**Comment by jean-philippe-martin** [comment]
java accepts relative paths, so as a small change consider using
target/gatk-tools-java-1.0-SNAPSHOT.jar
instead of
`pwd`/target/gatk-tools-java-1.0-SNAPSHOT.jar

(since this goes in the README it's worth making it as simple as possible)

Cheers,
JP

**Comment by pgrosu** [comment]
Hey JP,

Usually I would agree, but unfortunately for this implementation that approach would not work.  Below are two examples that demonstrate this:

```
$ java -jar -Dsamjdk.custom_reader=\
> https://www.googleapis.com/genomics,\
> com.google.cloud.genomics.gatk.htsjdk.GA4GHReaderFactory,\
> ./target/gatk-tools-java-1.0-SNAPSHOT.jar \
> -Dga4gh.client_secrets=client_secrets.json \
> dist/picard.jar ViewSam \
> INPUT=https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/
[Mon Mar 16 17:21:49 EDT 2015] picard.sam.ViewSam INPUT=https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/    ALIGNMENT_STATUS=All PF_STATUS=All HEADER_ONLY=false RECORDS_ONLY=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Mon Mar 16 17:21:49 EDT 2015] Executing as pgrosu@eofe5 on Linux 2.6.32-358.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_05-b13; Picard version: 1.129(b508b2885562a4e932d3a3a60b8ea283b7ec78e2_1424706677) IntelDeflater
INFO    2015-03-16 17:21:49     CustomReaderFactory     Attempting to open https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/ with custom factory
INFO    2015-03-16 17:21:49     CustomReaderFactory     Attempting to load factory class com.google.cloud.genomics.gatk.htsjdk.GA4GHReaderFactory from ./target/gatk-tools-java-1.0-SNAPSHOT.jar
ERROR   2015-03-16 17:21:49     CustomReaderFactory
java.lang.ClassNotFoundException: com.google.cloud.genomics.gatk.htsjdk.GA4GHReaderFactory
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:340)
        at htsjdk.samtools.CustomReaderFactory.getFactory(CustomReaderFactory.java:105)
        at htsjdk.samtools.CustomReaderFactory.maybeOpen(CustomReaderFactory.java:137)
        at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:210)
        at picard.sam.ViewSam.writeSamText(ViewSam.java:101)
        at picard.sam.ViewSam.doWork(ViewSam.java:84)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
[Mon Mar 16 17:21:51 EDT 2015] picard.sam.ViewSam done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=1063256064
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMFormatException: Unrecognized file format: htsjdk.samtools.seekablestream.SeekableHTTPStream@25bbf683
        at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:233)
        at picard.sam.ViewSam.writeSamText(ViewSam.java:101)
        at picard.sam.ViewSam.doWork(ViewSam.java:84)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
$
$
$ java -jar -Dsamjdk.custom_reader=\
> https://www.googleapis.com/genomics,\
> com.google.cloud.genomics.gatk.htsjdk.GA4GHReaderFactory,\
> target/gatk-tools-java-1.0-SNAPSHOT.jar \
> -Dga4gh.client_secrets=client_secrets.json \
> dist/picard.jar ViewSam \
> INPUT=https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/
[Mon Mar 16 17:22:05 EDT 2015] picard.sam.ViewSam INPUT=https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/    ALIGNMENT_STATUS=All PF_STATUS=All HEADER_ONLY=false RECORDS_ONLY=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Mon Mar 16 17:22:05 EDT 2015] Executing as pgrosu@eofe5 on Linux 2.6.32-358.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_05-b13; Picard version: 1.129(b508b2885562a4e932d3a3a60b8ea283b7ec78e2_1424706677) IntelDeflater
INFO    2015-03-16 17:22:05     CustomReaderFactory     Attempting to open https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/ with custom factory
INFO    2015-03-16 17:22:05     CustomReaderFactory     Attempting to load factory class com.google.cloud.genomics.gatk.htsjdk.GA4GHReaderFactory from target/gatk-tools-java-1.0-SNAPSHOT.jar
ERROR   2015-03-16 17:22:05     CustomReaderFactory
java.lang.ClassNotFoundException: com.google.cloud.genomics.gatk.htsjdk.GA4GHReaderFactory
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:340)
        at htsjdk.samtools.CustomReaderFactory.getFactory(CustomReaderFactory.java:105)
        at htsjdk.samtools.CustomReaderFactory.maybeOpen(CustomReaderFactory.java:137)
        at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:210)
        at picard.sam.ViewSam.writeSamText(ViewSam.java:101)
        at picard.sam.ViewSam.doWork(ViewSam.java:84)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
[Mon Mar 16 17:22:06 EDT 2015] picard.sam.ViewSam done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=1063780352
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMFormatException: Unrecognized file format: htsjdk.samtools.seekablestream.SeekableHTTPStream@25bbf683
        at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:233)
        at picard.sam.ViewSam.writeSamText(ViewSam.java:101)
        at picard.sam.ViewSam.doWork(ViewSam.java:84)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
$
```

While the following always will work:

```
$  java -jar -Dsamjdk.custom_reader=\
https://www.googleapis.com/genomics,\
com.google.cloud.genomics.gatk.htsjdk.GA4GHReaderFactory,\
`pwd`/gatk-tools-java-1.0-SNAPSHOT.jar \
-Dga4gh.client_secrets=client_secrets.json \
dist/picard.jar ViewSam \
INPUT=https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/
[Mon Mar 16 17:27:04 EDT 2015] picard.sam.ViewSam INPUT=https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/    ALIGNMENT_STATUS=All PF_STATUS=All HEADER_ONLY=false RECORDS_ONLY=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Mon Mar 16 17:27:04 EDT 2015] Executing as pgrosu@eofe5 on Linux 2.6.32-358.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_05-b13; Picard version: 1.129(b508b2885562a4e932d3a3a60b8ea283b7ec78e2_1424706677) IntelDeflater
INFO    2015-03-16 17:27:04     CustomReaderFactory     Attempting to open https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/ with custom factory
INFO    2015-03-16 17:27:04     CustomReaderFactory     Attempting to load factory class com.google.cloud.genomics.gatk.htsjdk.GA4GHReaderFactory from /home/pgrosu/me/gg_gatk/test/3-14-2015/gatk/gatk-tools-java-1.0-SNAPSHOT.jar
INFO    2015-03-16 17:27:04     CustomReaderFactory     Created custom factory for https://www.googleapis.com/genomics from com.google.cloud.genomics.gatk.htsjdk.GA4GHReaderFactory loaded from /home/pgrosu/me/gg_gatk/test/3-14-2015/gatk/gatk-tools-java-1.0-SNAPSHOT.jar
Mar 16, 2015 5:27:04 PM com.google.cloud.genomics.gatk.htsjdk.GA4GHSamRecordIterator seekMatchingRead
INFO: Getting firstinterval from the API
Mar 16, 2015 5:27:04 PM com.google.cloud.genomics.gatk.common.GenomicsApiDataSource getReadsFromGenomicsApi
INFO: Getting readset CK256frpGBD44IWHwLP22R4, sequence , start=0, end=0
Mar 16, 2015 5:27:04 PM com.google.cloud.genomics.gatk.common.GenomicsApiDataSource initGenomicsApi
INFO: Initializing Genomics API for https://www.googleapis.com/genomics/v1beta2
Mar 16, 2015 5:27:04 PM com.google.cloud.genomics.gatk.common.GenomicsApiDataSource initGenomicsApi
INFO: Using client secrets file client_secrets.json
Mar 16, 2015 5:27:06 PM com.google.cloud.genomics.gatk.common.GenomicsApiDataSource getReadsFromGenomicsApi
INFO: Found readset CK256frpGBD44IWHwLP22R4, dataset 15448427866823121459
Mar 16, 2015 5:27:06 PM com.google.cloud.genomics.gatk.common.GenomicsApiDataSource getReferences
INFO: Found read groups
Mar 16, 2015 5:27:06 PM com.google.cloud.genomics.gatk.common.GenomicsApiDataSource getReadsFromGenomicsApi
WARNING: Reference for sequence name  not found
Mar 16, 2015 5:27:06 PM com.google.cloud.genomics.gatk.common.GenomicsApiDataSource getReadsFromGenomicsApi
INFO: Searching for reads in sequence 0-0
Mar 16, 2015 5:27:06 PM com.google.cloud.genomics.gatk.common.GenomicsApiDataSource getUnmappedMatesOfMappedReads
INFO: Collecting unmapped mates of mapped reads for injection
Mar 16, 2015 5:27:06 PM com.google.cloud.genomics.gatk.common.GenomicsApiDataSource getUnmappedMatesOfMappedReads
INFO: Finished collecting unmapped mates of mapped reads: 36 found.
Mar 16, 2015 5:27:06 PM com.google.cloud.genomics.gatk.htsjdk.GA4GHSamRecordIterator queryNextInterval
INFO: Interval query took: 2.208 s
Mar 16, 2015 5:27:06 PM com.google.cloud.genomics.gatk.htsjdk.GA4GHSamRecordIterator seekMatchingRead
INFO: Got next interval from the API
Mar 16, 2015 5:27:06 PM com.google.cloud.genomics.gatk.common.GenomicsConverter makeSAMFileHeader
INFO: Getting @SQ header data from readgroupset info
@HD     VN:1.4  GO:none SO:coordinate
@SQ     SN:seq1 LN:5000
@SQ     SN:seq2 LN:5000
B7_591:4:96:693:509     73      seq1    1       99      36M     *       0       0       CACTAGTGGCTCATTGTAAATGTGTGGTTTAACTCG       <<<<<<<<<<<<<<<;<<<<<<<<<5<<<<<;:<;7    H0:i:1  H1:i:0     MF:i:18 NM:i:0  UQ:i:0  Aq:i:73
EAS54_65:7:152:368:113  73      seq1    3       99      35M     *       0       0       CTAGTGGCTCATTGTAAATGTGTGGTTTAACTCGT        <<<<<<<<<<0<<<<655<<7<<<:9<<3/:<6):     H0:i:1  H1:i:0     MF:i:18 NM:i:0  UQ:i:0  Aq:i:66
EAS51_64:8:5:734:57     137     seq1    5       99      35M     *       0       0       AGTGGCTCATTGTAAATGTGTGGTTTAACTCGTCC        <<<<<<<<<<<7;71<<;<;;<7;<<3;);3*8/5     H0:i:1  H1:i:0     MF:i:18 NM:i:0  UQ:i:0  Aq:i:66
B7_591:1:289:587:906    137     seq1    6       63      36M     *       0       0       GTGGCTCATTGTAATTTTTTGTTTTAACTCTTCTCT       (-&----,----)-)-),'--)---',+-,),''*,    H0:i:0  H1:i:0     MF:i:130        NM:i:5  UQ:i:38 Aq:i:63
EAS56_59:8:38:671:758   137     seq1    9       99      35M     *       0       0       GCTCATTGTAAATGTGTGGTTTAACTCGTCCATGG        <<<<<<<<<<<<<<<;<;7<<<<<<<<7<<;:<5%     H0:i:1  H1:i:0     MF:i:18 NM:i:0  UQ:i:0  Aq:i:72
EAS114_28:5:296:340:699 137     seq1    13      99      36M     *       0       0       ATTGTAAATGTGTGGTTTAACTCGTCCATGGCCCAG       <<<<<;<<<;<;<<<<<<<<<<<8<8<3<8;<;<0;    H0:i:1  H1:i:0     MF:i:18 NM:i:0  UQ:i:0  Aq:i:73
EAS56_61:6:18:467:281   73      seq1    13      99      35M     *       0       0       ATTGTAAATGTGTGGTTTAACTCGTCCCTGGCCCA        <<<<<<<<;<<<8<<<<<;8:;6/686&;(16666     H0:i:0  H1:i:1     MF:i:18 NM:i:1  UQ:i:5  Aq:i:39
...
```
~p

**Comment by jean-philippe-martin** [comment]
ok then, you were right! Sorry about the diversion.

**Comment by pgrosu** [comment]
Absolutely no worries, and I don't feel it's a diversion :)  I prefer any question or discussion - this way there are no assumptions and we can advance the code together as a community in the optimal way.  Trust me, I'm not perfect :)

So keep 'em coming,
~p

**Comment by pgrosu** [comment]
Hi Ilia, 

This is awesome, but there are still a few of minor things:

1) Regarding the backticks and how they appear in Github.  You might what to use the backslash to enforce the backtick to appear like this - currently the example with pwd has them missing in the Readme file:

```
\`
```
2) Regarding the jar file, now it's up to version 1.1 but the example in the Readme still shows 1.0.  So maybe a quick update/merge to the example with the following would help new users, since currently it fails - and it would be nice to show users that they should put Picard in the `dist` directory:

java -jar -Dsamjdk.custom_reader=\
-Dsamjdk.custom_reader=https://www.googleapis.com/genomics,\
com.google.cloud.genomics.gatk.htsjdk.GA4GHReaderFactory,\
\`pwd\`/target/gatk-tools-java-1.1-SNAPSHOT.jar \
-Dga4gh.client_secrets=client_secrets.json \
dist/picard.jar ViewSam \
INPUT=https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/

3) Currently with the above updates, it now throws the following error when I run it:

```Bash
$ java -jar -Dsamjdk.custom_reader=\
> -Dsamjdk.custom_reader=https://www.googleapis.com/genomics,\
> com.google.cloud.genomics.gatk.htsjdk.GA4GHReaderFactory,\
> `pwd`/target/gatk-tools-java-1.1-SNAPSHOT.jar \
> -Dga4gh.client_secrets=client_secrets.json \
> dist/picard.jar ViewSam \
> INPUT=https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/
[Wed Mar 25 21:24:11 EDT 2015] picard.sam.ViewSam INPUT=https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/    ALIGNMENT_STATUS=All PF_STATUS=All HEADER_ONLY=false RECORDS_ONLY=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Wed Mar 25 21:24:11 EDT 2015] Executing as pgrosu@eofe5 on Linux 2.6.32-358.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_05-b13; Picard version: 1.129(b508b2885562a4e932d3a3a60b8ea283b7ec78e2_1424706677) IntelDeflater
[Wed Mar 25 21:24:13 EDT 2015] picard.sam.ViewSam done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=1065353216
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMFormatException: Unrecognized file format: htsjdk.samtools.seekablestream.SeekableHTTPStream@12c8a2c0
        at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:233)
        at picard.sam.ViewSam.writeSamText(ViewSam.java:101)
        at picard.sam.ViewSam.doWork(ViewSam.java:84)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
$
```

~p

**Pull request merged**
