### PR TITLE
Add Maven POM file, and correct some compilation problems with Stopwatch...

### PR DESCRIPTION
**Pull request by wbrockman**
... and getResourceDescription.

### CODE REVIEW

**Comment by wbrockman** [comment]
(First ever GitHub pull request, apologies if I've screwed it up!) 

I think this Maven file will suffice to let me work with this repo.  To get it to compile I needed a couple of little fixes.

**Comment by iliat** [comment]
@wbrockman , we can probably go with your change over mine since in between htsjdk finally made it into the central repo, so we do not need the contortions of local install script like in my PR.
What was the compilation problem with StopWatch - it compiles fine for me, so I am guessing there is some library version problem ?

**Comment by pgrosu** [comment]
Yeah, it compiles fine for me as well:

```
$ mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building gatk-tools-java 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/com/github/samtools/htsjdk/1.128/htsjdk-1.128.pom
Downloaded: http://repo.maven.apache.org/maven2/com/github/samtools/htsjdk/1.128/htsjdk-1.128.pom (3 KB at 7.8 KB/sec)
...
[INFO] Copying google-api-client-1.19.0.jar to /home/pgrosu/me/gg_gatk/test_with_maven/gatk-tools-java/target/dependency/google-api-client-1.19.0.jar
[INFO] Copying google-api-services-genomics-v1beta2-rev7-1.19.0.jar to /home/pgrosu/me/gg_gatk/test_with_maven/gatk-tools-java/target/dependency/google-api-services-genomics-v1beta2-rev7-1.19.0.jar
[INFO] Copying httpclient-4.0.1.jar to /home/pgrosu/me/gg_gatk/test_with_maven/gatk-tools-java/target/dependency/httpclient-4.0.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.908 s
[INFO] Finished at: 2015-02-17T23:48:02-05:00
[INFO] Final Memory: 22M/120M
[INFO] ------------------------------------------------------------------------
$
```
Looks like the changes are here:

https://github.com/googlegenomics/gatk-tools-java/pull/9/files

Thanks guys,
~p

**Comment by wbrockman** [comment]
The StopWatch issue is (if I understand correctly) that your build was previously using an old version of Guava.  Here are the current docs for StopWatch: 

http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Stopwatch.html

As documented now, it doesn't have a public constructor or a elapsedMillis method, so I replaced the uses of those methods with the current equivalents. I suspect you were getting the really old version of Guava that is part of the google APIs dependency (which was then breaking my build when I tried to depend on this code).

**Comment by iliat** [comment]
LGTM

**Pull request merged**
