### PR TITLE
Documentation for adding ga4gh support

### PR DESCRIPTION
**Pull request by iliat**

### CODE REVIEW

**Comment by deflaux** [comment]
@iliat Can you please also go ahead and add the link to this new page from README.md so that I can see how this code-specific documentation on github all fits together?

**Comment by iliat** [comment]
Ah good point, I will add that to PR.
  Ilia.

**Comment by iliat** [comment]
Btw, the reason CLA check was triggering is because I committed from my mac client and did not have my email set properly in git. Now fixed.

**Comment by iliat** [comment]
@deflaux Added

**Comment by iliat** [comment]
@deflaux Fixed to be relative link

**Pull request merged**
