### PR TITLE
Add Maven support

### PR DESCRIPTION
**Pull request by iliat**
Unfortunately, without latest version of HTSJDK in central repository we can not push this to central repository either, so have to wait for https://github.com/samtools/htsjdk/pull/115 to be resolved. However this still adds the necessary pom.xml and a shell script that installs the HSTJDK into a local maven repository.
To build:
cd lib
./install_htsjdk_maven.sh
cd ..
mvn compile
mvn package

### CODE REVIEW

**Comment by dionloy** [comment]
LGTM

(If I'm parsing your comment correctly, this shouldn't be merged until htsjdk has its support in place?  Or okay to merge, since no one is actually using Maven for gatk-tools-java anyway yet).

**Comment by iliat** [comment]
@dionloy Its ok to merge as is, since I have an htsjdk jarlocally and a script to install it into internal repo.

**Comment by wbrockman** [comment]
Note that samtools/htsjdk#115 has now been merged.

**Comment by iliat** [comment]
Closing this in favor of Will's

**Pull request closed without merging**
